//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.15 at 12:55:10 PM MSK 
//


package ru.innopolis.xjc;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="comment">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="conetnt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="author_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="course_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "comment"
})
@XmlRootElement(name = "comments")
public class Comments {

    @XmlElement(required = true)
    protected Comments.Comment comment;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link Comments.Comment }
     *     
     */
    public Comments.Comment getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comments.Comment }
     *     
     */
    public void setComment(Comments.Comment value) {
        this.comment = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="conetnt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="author_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="course_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "conetnt",
        "authorId",
        "courseId"
    })
    public static class Comment {

        @XmlElement(required = true)
        protected BigInteger id;
        @XmlElement(required = true)
        protected String conetnt;
        @XmlElement(name = "author_id", required = true)
        protected BigInteger authorId;
        @XmlElement(name = "course_id", required = true)
        protected BigInteger courseId;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setId(BigInteger value) {
            this.id = value;
        }

        /**
         * Gets the value of the conetnt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConetnt() {
            return conetnt;
        }

        /**
         * Sets the value of the conetnt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConetnt(String value) {
            this.conetnt = value;
        }

        /**
         * Gets the value of the authorId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAuthorId() {
            return authorId;
        }

        /**
         * Sets the value of the authorId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAuthorId(BigInteger value) {
            this.authorId = value;
        }

        /**
         * Gets the value of the courseId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCourseId() {
            return courseId;
        }

        /**
         * Sets the value of the courseId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCourseId(BigInteger value) {
            this.courseId = value;
        }

    }

}
